services:
  board_api:
    build:
      context: .
      dockerfile: board_api/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - auth
    ports:
      - "3002:3002"
    networks:
      - backend

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    networks:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - backend

  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    depends_on:
    - auth
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend


volumes:
  dbdata:

networks:
  backend: